POST http://localhost:3000/ticket-payment/buy-tickets
Content-Type: application/json

{
    "cpf": "12345678901",
    "name": "John Doe",
    "email": "john@example.com",
    "number": "11999999999",
    "ticket_amount": 500,
    "raffle_edition_id": "abcfea60-589d-4895-88e1-135db9689097"
}
###
GET http://localhost:3000/ticket-queue/clear

###
POST http://localhost:3000/raffle-editions/
Content-Type: application/json

{
  "title": "Raffle Edition Test",
  "description": "This is a test",
  "status": "pending",
  "total_tickets": 1010,
  "price": "1.00",
  "raffle_draw_date": "2022-12-25T00:00:00.000Z",
  "prizes": [
    {
      "quantity": 1000,
      "prize_id": "f22476ef-ecc2-433a-a176-1d6db6668205"
    }
  ]
}

###
POST http://localhost:3000/prizes/
Content-Type: application/json

{
    "prize_name": "money",
    "prize_quantity": 1000
}